# keys have a buffer size of 512 for now
KEY_HOME          = 0xff50
KEY_ENTER         = 13
KEY_ESC           = 27
KEY_LEFT          = 37
KEY_UP            = 38
KEY_RIGHT         = 39
KEY_DOWN          = 40
KEY_W             = 87
KEY_A             = 65
KEY_S             = 83
KEY_D             = 68
KEY_Q             = 81
KEY_J             = 74
KEY_CTRL          = 17
KEY_SPACE         = 32
KEY_PAGEUP        = 0xff55
KEY_PAGEDOWN      = 0xff56
KEY_END           = 0xff57
KEY_BEGIN         = 0xff58
KEY_V_LEFT        = "v_left"
KEY_V_RIGHT       = "v_right"
KEY_V_UP          = "v_up"
KEY_V_DOWN        = "v_down"
KEY_V_FIRE        = "v_fire"
SEMAPHORE1        = 500
SEMAPHORE2        = 501

MOUSE_LEFT        = 0xe000
MOUSE_RIGHT       = 0xe001
MOUSE_WHEEL       = 0xe002

CMD_DRAWLINE      = 1
CMD_CLEAR         = 2
CMD_DRAWIMAGE     = 3
CMD_LOADSOUND     = 4
CMD_PLAYSOUND     = 5
CMD_PAUSESOUND    = 6
CMD_DRAWTEXT      = 7
CMD_DRAWPIXEL     = 8
CMD_DRAWRECT      = 9
CMD_DRAWCIRCLE    = 10
CMD_REVEAL        = 11
CMD_HALT          = 12
CMD_PRINT         = 13
CMD_INPUT         = 14
CMD_TRTL_FORWARD  = 15
CMD_TRTL_RIGHT    = 16
CMD_TRTL_LEFT     = 17
CMD_TRTL_CLEAR    = 18
CMD_TRTL_SPEED    = 19
CMD_TRTL_ROTATE_SPD= 20
CMD_TRTL_HIDE     = 21
CMD_TRTL_SHOW     = 22
CMD_TRTL_PENUP    = 23
CMD_TRTL_PENDOWN  = 24
CMD_TRTL_BEGINFILL= 25
CMD_TRTL_ENDFILL  = 26
CMD_TRTL_REVEAL   = 27
CMD_TRTL_PENCOLOR = 28
CMD_TRTL_FILLCOLOR= 29